backend:
  name: 'git-gateway'
  branch: 'migration-V2'

# publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  #  Page Project
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: src/markdown/projects
    create: true
    fields:
      - { name: 'templateKey', widget: 'hidden', default: 'project' }
      - { name: 'cover', label: 'Cover Image', widget: 'image' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'summary', label: 'Summary', widget: 'text' }
      - { name: 'git', label: 'Git Url', widget: 'string' }
      - { name: 'web', label: 'Web Url', widget: 'string' }
      - { name: 'tags', label: 'Tags' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
  #  Page Resume
  - name: 'pages'
    label: 'Pages'
    delete: false
    files:
      - name: 'resume'
        label: 'Resume'
        file: 'src/markdown/resume.md'
        fields:
          - { name: 'body', label: 'Body', widget: 'markdown' }
