backend:
  name: 'git-gateway'
  branch: 'master'

# publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  #  Page Project
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: src/markdown/projects
    create: true
    fields:
      - {
          name: 'templateKey',
          widget: 'hidden',
          default: 'project',
          required: true,
        }
      - { name: 'cover', label: 'Cover Image', widget: 'image', required: true }
      - { name: 'date', label: 'Date', widget: 'date', required: true }
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - { name: 'summary', label: 'Summary', widget: 'text', required: true }
      - { name: 'git', label: 'Git Url', widget: 'string', required: false }
      - { name: 'web', label: 'Web Url', widget: 'string', required: false }
      - { name: 'tags', label: 'Tags', required: true }
      - { name: 'body', label: 'Body', widget: 'markdown' }
  #  Page Resume
  - name: 'pages'
    label: 'Pages'
    delete: false
    files:
      - name: 'resume'
        label: 'Resume'
        file: 'src/markdown/resume.md'
        fields:
          - { name: 'body', label: 'Resume Content', widget: 'markdown' }
